# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avaliacaoArtigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artigo', models.IntegerField(verbose_name='id_artigo')),
                ('id_avaliador', models.IntegerField(verbose_name='id_avaliador')),
                ('nota', models.FloatField(verbose_name='nota')),
            ],
        ),
    ]
